package Modelo;
// Generated 25/08/2017 03:38:44 PM by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private String usuario;
     private String contraseña;

    public Admin() {
    }

    public Admin(String usuario, String contraseña) {
       this.usuario = usuario;
       this.contraseña = contraseña;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContraseña() {
        return this.contraseña;
    }
    
    public void setContraseña(String contraseña) {
        this.contraseña = contraseña;
    }

}


