package Modelo;
// Generated 25/08/2017 03:38:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer idalumno;
     private Curso curso;
     private String ciAlumno;
     private String nombre;
     private String apellido;
     private String telefono;
     private String correo;
     private int estado;
     private Date fechaNacimiento;
     private byte[] foto;

    public Alumno() {
    }

	
    public Alumno(Curso curso, String ciAlumno, String nombre, String apellido, String telefono, String correo, int estado, Date fechaNacimiento) {
        this.curso = curso;
        this.ciAlumno = ciAlumno;
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefono = telefono;
        this.correo = correo;
        this.estado = estado;
        this.fechaNacimiento = fechaNacimiento;
    }
    public Alumno(Curso curso, String ciAlumno, String nombre, String apellido, String telefono, String correo, int estado, Date fechaNacimiento, byte[] foto) {
       this.curso = curso;
       this.ciAlumno = ciAlumno;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.correo = correo;
       this.estado = estado;
       this.fechaNacimiento = fechaNacimiento;
       this.foto = foto;
    }
   
    public Integer getIdalumno() {
        return this.idalumno;
    }
    
    public void setIdalumno(Integer idalumno) {
        this.idalumno = idalumno;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getCiAlumno() {
        return this.ciAlumno;
    }
    
    public void setCiAlumno(String ciAlumno) {
        this.ciAlumno = ciAlumno;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }




}


