package Modelo;
// Generated 25/08/2017 03:38:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer idCurso;
     private Instructor instructor;
     private String nombreCurso;
     private int tope;
     private String dia;
     private String hora;
     private String aula;
     private int estadoAula;
     private int estadoCurso;
     private Set alumnos = new HashSet(0);

    public Curso() {
    }

	
    public Curso(Instructor instructor, String nombreCurso, int tope, String dia, String hora, String aula, int estadoAula, int estadoCurso) {
        this.instructor = instructor;
        this.nombreCurso = nombreCurso;
        this.tope = tope;
        this.dia = dia;
        this.hora = hora;
        this.aula = aula;
        this.estadoAula = estadoAula;
        this.estadoCurso = estadoCurso;
    }
    public Curso(Instructor instructor, String nombreCurso, int tope, String dia, String hora, String aula, int estadoAula, int estadoCurso, Set alumnos) {
       this.instructor = instructor;
       this.nombreCurso = nombreCurso;
       this.tope = tope;
       this.dia = dia;
       this.hora = hora;
       this.aula = aula;
       this.estadoAula = estadoAula;
       this.estadoCurso = estadoCurso;
       this.alumnos = alumnos;
    }
   
    public Integer getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }
    public Instructor getInstructor() {
        return this.instructor;
    }
    
    public void setInstructor(Instructor instructor) {
        this.instructor = instructor;
    }
    public String getNombreCurso() {
        return this.nombreCurso;
    }
    
    public void setNombreCurso(String nombreCurso) {
        this.nombreCurso = nombreCurso;
    }
    public int getTope() {
        return this.tope;
    }
    
    public void setTope(int tope) {
        this.tope = tope;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public String getAula() {
        return this.aula;
    }
    
    public void setAula(String aula) {
        this.aula = aula;
    }
    public int getEstadoAula() {
        return this.estadoAula;
    }
    
    public void setEstadoAula(int estadoAula) {
        this.estadoAula = estadoAula;
    }
    public int getEstadoCurso() {
        return this.estadoCurso;
    }
    
    public void setEstadoCurso(int estadoCurso) {
        this.estadoCurso = estadoCurso;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }




}


