package Modelo;
// Generated 25/08/2017 03:38:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Instructor generated by hbm2java
 */
public class Instructor  implements java.io.Serializable {


     private Integer idInstructor;
     private String ciInstructor;
     private String nombreInstructor;
     private String apellidoInstructor;
     private String especialidad;
     private String correoInstructor;
     private String tlfInstructor;
     private int estadoInstructor;
     private Set cursos = new HashSet(0);

    public Instructor() {
    }

	
    public Instructor(String ciInstructor, String nombreInstructor, String apellidoInstructor, String especialidad, String correoInstructor, String tlfInstructor, int estadoInstructor) {
        this.ciInstructor = ciInstructor;
        this.nombreInstructor = nombreInstructor;
        this.apellidoInstructor = apellidoInstructor;
        this.especialidad = especialidad;
        this.correoInstructor = correoInstructor;
        this.tlfInstructor = tlfInstructor;
        this.estadoInstructor = estadoInstructor;
    }
    public Instructor(String ciInstructor, String nombreInstructor, String apellidoInstructor, String especialidad, String correoInstructor, String tlfInstructor, int estadoInstructor, Set cursos) {
       this.ciInstructor = ciInstructor;
       this.nombreInstructor = nombreInstructor;
       this.apellidoInstructor = apellidoInstructor;
       this.especialidad = especialidad;
       this.correoInstructor = correoInstructor;
       this.tlfInstructor = tlfInstructor;
       this.estadoInstructor = estadoInstructor;
       this.cursos = cursos;
    }
   
    public Integer getIdInstructor() {
        return this.idInstructor;
    }
    
    public void setIdInstructor(Integer idInstructor) {
        this.idInstructor = idInstructor;
    }
    public String getCiInstructor() {
        return this.ciInstructor;
    }
    
    public void setCiInstructor(String ciInstructor) {
        this.ciInstructor = ciInstructor;
    }
    public String getNombreInstructor() {
        return this.nombreInstructor;
    }
    
    public void setNombreInstructor(String nombreInstructor) {
        this.nombreInstructor = nombreInstructor;
    }
    public String getApellidoInstructor() {
        return this.apellidoInstructor;
    }
    
    public void setApellidoInstructor(String apellidoInstructor) {
        this.apellidoInstructor = apellidoInstructor;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public String getCorreoInstructor() {
        return this.correoInstructor;
    }
    
    public void setCorreoInstructor(String correoInstructor) {
        this.correoInstructor = correoInstructor;
    }
    public String getTlfInstructor() {
        return this.tlfInstructor;
    }
    
    public void setTlfInstructor(String tlfInstructor) {
        this.tlfInstructor = tlfInstructor;
    }
    public int getEstadoInstructor() {
        return this.estadoInstructor;
    }
    
    public void setEstadoInstructor(int estadoInstructor) {
        this.estadoInstructor = estadoInstructor;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


